# Generated by Django 5.1.6 on 2025-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap', models.BigIntegerField()),
            ],
        ),
    ]
